---

git_package: git

git_packages: [
  git
]

git_config: [
#   { key: 'credential.helper', value: '', scope: 'global' },
  { key: 'http.sslVerify', value: 'true', scope: 'global' },
#   { key: 'user.email', value: '', scope: 'global' },
#   { key: 'user.name', value: '', scope: 'global' }
]
