---

# https://docs.docker.com/registry/
# docker run -d -p 5000:5000 --name registry registry:2
- name: "Run image {{ registry.image.name }}:{{ registry.image.tag }} as service {{ registry.service.name }}"
  docker_container:
    name: "{{ registry.service.name }}"
    image: "{{ registry.image.name }}:{{ registry.image.tag }}"
    env:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry_data
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_DEBUG_ADDR: 0.0.0.0:5001
    published_ports:
      - "{{ registry.service.ports.http }}:5000"
      - 5001:5001
    restart_policy: always
    state: started
    volumes:
      - /registry_data

- name: "register {{ registry.service.name }} service with the local consul agent"
  consul:
    service_name: "{{ registry.service.name }}-{{ item.value }}"
    service_port: "{{ item.value }}"
  with_dict: "{{ registry.service.ports }}"
  when: service_consul_running and registry.service.ports is defined

  # registry:
  #   image: library/registry:2.6
  #   environment:
  #     REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry_data
  #     REGISTRY_STORAGE_DELETE_ENABLED: "true"

  #     REGISTRY_HTTP_ADDR: 0.0.0.0:5000
  #     REGISTRY_HTTP_DEBUG_ADDR: 0.0.0.0:5001

  #     REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /etc/docker/registry/portus.crt

  #     REGISTRY_AUTH_TOKEN_REALM: http://${MACHINE_FQDN}:3000/v2/token
  #     REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}:${REGISTRY_PORT}
  #     REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}

  #     REGISTRY_NOTIFICATIONS_ENDPOINTS: >
  #       - name: portus
  #         url: http://${MACHINE_FQDN}:3000/v2/webhooks/events
  #         timeout: 2000ms
  #         threshold: 5
  #         backoff: 1s
  #   volumes:
  #     - /registry_data
  #     - ./examples/development/compose/portus.crt:/etc/docker/registry/portus.crt:ro
  #   ports:
  #     - ${REGISTRY_PORT}:5000
  #     - 5001:5001
  #   links:
  #     - portus