---

- name: Get source
  git:
    repo: "{{ drawio.project.src }}"
    dest: "/tmp/drawio"
    update: yes
  register: drawio_source

- name: Build image
  docker_image:
    path: "/tmp/drawio/{{ drawio.image.base | default(debian) }}"
    name: "{{ drawio.image.name }}"
    tag: "{{ drawio.image.tag}}"
  when: drawio_source.changed

# docker run -it --rm --name="draw" -p 8080:8080 -p 8443:8443 fjudith/draw.io
# go to http://localhost:8080/?offline=1&https=0 or https://localhost:8443/?offline=1
- name: "Run image {{ drawio.image.name }}:{{ drawio.image.tag }} as container {{ drawio.container.name }}"
  docker_container:
    name: "{{ drawio.container.name }}"
    image: "{{ drawio.image.name }}:{{ drawio.image.tag }}"
    # dns_servers:
    #   - "{{ consul_server }}"
    # dns_search_domains:
    #   - service.consul
    # hostname: "{{ drawio.container.name }}"
    # network_mode: host
    published_ports:
      - "{{ drawio.container.ports.http }}:8080"
      - "{{ drawio.container.ports.https }}:8443"
    recreate: yes
    restart_policy: "{{ drawio.container.restart.policy }}"
    state: started
  register: drawio_container_launched
  