---
# file: roles/pip/tasks/install.yml

# based on: https://pip.pypa.io/en/stable/installing/

- name: Check if "{{ item.pip }}" is installed
  command: "{{ item.pip }} --version"
  ignore_errors: true
  changed_when: false # read-only task
  check_mode: no
  register: pip_install_check

- name: download get-pip.py
  get_url:
    url: "{{ pip_source_url }}"
    dest: "{{ pip_download_dest }}"
  when: pip_install_check.rc != 0

- name: "Install {{ item.pip }}"
  become: yes
  command: "{{ item.python }} {{ pip_download_dest }}/get-pip.py"
  tags:
    - installation
    - pip
  when: pip_install_check.rc != 0

- name: "upgrade {{ item.pip }} if installed"
  become: yes
  pip:
    name: pip
    # extra_args: --user
    state: latest
  tags:
    - upgrade
    - pip
  when: pip_install_check.rc == 0

# - name: set path file
#   set_fact:
#     var_file: "{{ ansible_user_dir }}/.profile"

# - name: "add path to {{ ansible_user_dir }}/.profile"
#   blockinfile:
#     path: "{{ ansible_user_dir }}/.profile" # required. The file to modify.,Before 2.3 this option was only usable as I(dest), I(destfile) and I(name).
#     backup: yes # not required. Create a backup file including the timestamp information so you can get the original file back if you somehow clobbered it incorrectly.
#     create: yes # not required. Create a new file if it doesn't exist.
#     state: present # not required. choices: absent;present. Whether the block should be there or not.
#     block: |
#       if [ -d "$HOME/.local/bin" ] ; then
#         PATH="$HOME/.local/bin:$PATH"
#       fi
#     marker: "# {mark} ANSIBLE MANAGED BLOCK pip path"
