---

- name: Install or upgrade pip
  include_tasks:
    file: install.yml
  loop: "{{ pip_versions }}"

- name: delete get-pip.py
  file:
    path: "{{ pip_download_dest }}/get-pip.py"
    state: absent
