---

- name: "Check if {{ git_package }} is installed"
  command: "{{ git_package }} --version"
  ignore_errors: true
  changed_when: false # read-only task
  check_mode: no
  register: git_install_check

- name: "Install {{ git_package }}"
  import_tasks: install.yml
  when: git_install_check.rc != 0

- name: "Configure {{ git_package }}"
  import_tasks: configure.yml
  when: git_install_check.rc == 0 or git_installed