---

- hosts: local-system # rpi-home-network-nodes

  tasks:

    - import_role:
        name: portus
        # tasks_from: nomad.yml
        tasks_from: container.yml
      environment:
        NOMAD_ADDR: "http://{{ ansible_default_ipv4.address }}:4646"
      tags:
        - portus
